<?php

return [
    "groups" =>
        [
            "label" => "General",
            "code" => "general",
            "variables" => [
                [
                    "variable" => "store_url",
                    "label" => "Store URL",
                    "type" => "string",
                    "source" => ["Website", "Channel", "Store"],
                    "column_type" => "",
                    "column" => "",
                    "availability" => ["all"]
                ],
                [
                    "variable" => "store_name",
                    "label" => "Store Name",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                    "column" => "email",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_phone_number",
                    "label" => "Store Phone Number",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                    "column" => "email",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_country",
                    "label" => "Store Country",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                    "column" => "email",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_state",
                    "label" => "Store Region / State",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                    "column" => "email",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_post_code",
                    "label" => "Store Postal / Zip Code",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_city",
                    "label" => "Store City",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_address_line_1",
                    "label" => "Store Address Line 1",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_address_line_2",
                    "label" => "Store Address Line 2",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_vat_number",
                    "label" => "Store VAT number",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_email_address",
                    "label" => "Store Email Address",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
                [
                    "variable" => "store_email_logo_url",
                    "label" => "Store Email Logo URL",
                    "type" => "string",
                    "source" => "configuration",
                    "column_type" => "",
                "column" => "",
                    "availability" => ["all"],
                ],
            ],
        ],

    [
        "label" => "Customer",
        "code" => "customer",
        "variables" => [
            [
                "variable" => "customer_id",
                "label" => "Customer ID",
                "type" => "integer",
                "source" => "Modules\Customer\Entities\Customer",
                "column_type" => "",
                "column" => "id",
                "availability" => ["new_account", "welcome_email", "forgot_password", "reset_password", "new_order", "order_update"],
            ],
            [
                "variable" => "customer_name",
                "label" => "Customer Name",
                "type" => "string",
                "source" => "Modules\Customer\Entities\Customer",
                "column_type" => "array",
                "column" => [ "first_name","middle_name", "last_name" ],
                "availability" => ["new_account", "welcome_email", "forgot_password", "reset_password", "new_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "customer_email_address",
                "label" => "Customer Email Address",
                "type" => "string",
                "source" => "Modules\Customer\Entities\Customer",
                "column_type" => "",
                "column" => "email",
                "availability" => ["new_account", "welcome_email", "forgot_password", "reset_password", "new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "customer_dashboard_url",
                "label" => "Customer Dashboard URL",
                "type" => "string",
                "source" => "Modules\Customer\Entities\Customer",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_account", "welcome_email", "forgot_password", "reset_password", "new_order", "order_update"],
            ],
            [
                "variable" => "account_confirmation_url",
                "label" => "Account Confirmation URL",
                "type" => "string",
                "source" => "Modules\Customer\Entities\Customer",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_account"],
            ],
        ],
    ],

    [
        "label" => "Password Reset",
        "code" => "password reset",
        "variables" => [
            [
                "variable" => "password_reset_url",
                "label" => "Password Reset URL",
                "type" => "",
                "source" => "",
                "column_type" => "",
                "column" => "",
                "availability" => ["forgot_password"],
            ],
        ],
    ],

    [
        "label" => "Order",
        "code" => "order",
        "variables" => [
            [
                "variable" => "order_id",
                "label" => "Order ID",
                "type" => "integer",
                "source" => "Modules\Country\Entities\Country",
                "column_type" => "",
                "column" => "id",
                "availability" => ["new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "order_items",
                "label" => "Order Items (Table)",
                "type" => "",
                "source" => "",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "billing_address",
                "label" => "Billing Address",
                "type" => "object",
                "source" => "",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "shipping_address",
                "label" => "Shipping Address",
                "type" => "",
                "source" => "",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
            [
                "variable" => "order",
                "label" => "Order",
                "type" => "",
                "source" => "",
                "column_type" => "",
                "column" => "",
                "availability" => ["new_order", "new_guest_order", "order_update", "order_update_guest"],
            ],
        ]
    ]
];
